[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
rootDirectory = "backend"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api"
healthcheckTimeout = 100
